function [E, J, A, rho] = evaluate_structural_properties(x_grid, t_grid, ST_cell)

x_grid = mod(x_grid, sum(arrayfun(@(obj) obj.Beam.L, ST_cell)));
L = cumsum(reshape([ ...
    arrayfun(@(obj) obj.Piezo.L, ST_cell) ...
    arrayfun(@(obj) obj.Beam.L - obj.Piezo.L, ST_cell) ...
    ]', [], 1));

E = ...
    (x_grid >= 0 & x_grid < L(1)) .* ST_cell(1).E{1}(t_grid) + ...
    (x_grid >= L(1) & x_grid < L(2)) .* ST_cell(1).E{2}(t_grid) + ...
    (x_grid >= L(2) & x_grid < L(3)) .* ST_cell(2).E{1}(t_grid) + ...
    (x_grid >= L(3) & x_grid < L(4)) .* ST_cell(2).E{2}(t_grid) + ...
    (x_grid >= L(4) & x_grid < L(5)) .* ST_cell(3).E{1}(t_grid) + ...
    (x_grid >= L(5) & x_grid <= L(6)) .* ST_cell(3).E{2}(t_grid);

A = ...
    (x_grid >= 0 & x_grid < L(1)) .* ST_cell(1).A{1} + ...
    (x_grid >= L(1) & x_grid < L(2)) .* ST_cell(1).A{2} + ...
    (x_grid >= L(2) & x_grid < L(3)) .* ST_cell(2).A{1} + ...
    (x_grid >= L(3) & x_grid < L(4)) .* ST_cell(2).A{2} + ...
    (x_grid >= L(4) & x_grid < L(5)) .* ST_cell(3).A{1} + ...
    (x_grid >= L(5) & x_grid <= L(6)) .* ST_cell(3).A{2};

J = ...
    (x_grid >= 0 & x_grid < L(1)) .* ST_cell(1).J{1} + ...
    (x_grid >= L(1) & x_grid < L(2)) .* ST_cell(1).J{2} + ...
    (x_grid >= L(2) & x_grid < L(3)) .* ST_cell(2).J{1} + ...
    (x_grid >= L(3) & x_grid < L(4)) .* ST_cell(2).J{2} + ...
    (x_grid >= L(4) & x_grid < L(5)) .* ST_cell(3).J{1} + ...
    (x_grid >= L(5) & x_grid <= L(6)) .* ST_cell(3).J{2};

rho = ...
    (x_grid >= 0 & x_grid < L(1)) .* ST_cell(1).rho{1} + ...
    (x_grid >= L(1) & x_grid < L(2)) .* ST_cell(1).rho{2} + ...
    (x_grid >= L(2) & x_grid < L(3)) .* ST_cell(2).rho{1} + ...
    (x_grid >= L(3) & x_grid < L(4)) .* ST_cell(2).rho{2} + ...
    (x_grid >= L(4) & x_grid < L(5)) .* ST_cell(3).rho{1} + ...
    (x_grid >= L(5) & x_grid <= L(6)) .* ST_cell(3).rho{2};

end
