clc
clear variables
% close all

%% Beam data

% Odd elements corresponds to sandwiched beams section
beam = struct( ...
    'E', 69e9, ...
    'h', 1e-3, ...
    'b', 20e-3, ...
    'L', [690 576 1134] * 1e-3, ...
    'rho', 2700 ...
    );

beam.A(:) = beam.b(:) .* beam.h(:);
beam.J(:) = beam.b(:) .* (beam.h(:).^3) / 12;

% % Define a single cell as an array of 3 piezos
% fields = fieldnames(beam);
% for i = 1:numel(fields)
%     beam.(fields{i}) = repmat(beam.(fields{i}), 1, 3);
% end


%% Piezo data

piezo = struct( ...
    'Y11_E', 62e9, ...
    'C_T', 7.0e-9, ...
    'k31', 0.351, ...
    'h', 1e-3, ...
    'b', 20e-3, ...
    'L', 22e-3, ...
    'rho', 7900);

piezo.A = piezo.b .* piezo.h;
piezo.J = piezo.b * (piezo.h^3) / 12 + piezo.A * (beam.h(1)/2 + piezo.h/2)^2;
piezo.C_S = piezo.C_T * (1 - piezo.k31^2);


%% Shunt data

shunt = struct( ...
    'R0', 1000e3, ...
    'R1', 7.5e3, ...
    'R2', 13.7e3, ...
    'C0', 4.4e-9, ...
    'L', 15e-3, ...
    'R', 1e3);


%% Parameters saving to '.mat' file

save("analysis\parameters.mat")